### ISSUE TITLE
[FEATURE REQUEST] Be able to select a dll file to inject once the game is launched (clients)

### ISSUE THREAD

**Issue by CoadyKidd** [BedrockLauncher/BedrockLauncher.GitHub.io#13]
I think this should be added as it would be easier to use clients and it would be like java edition

**Comment by tresabhi** [comment]
Please make feature requests for the launcher over at the [launcher's repository page](https://github.com/BedrockLauncher/BedrockLauncher/issues). This repository is just for the website.
